get_property(_is_defined GLOBAL PROPERTY _find_target_utility_func_defined DEFINED)
if(_is_defined)
	return()
endif()
define_property(GLOBAL PROPERTY _find_target_utility_func_defined)

macro(_find_target_move_to_parent_scope list_var)
	foreach(var ${list_var})
		if(DEFINED ${var})
			set(${var} "${${var}}" PARENT_SCOPE)
		endif()
	endforeach()
endmacro()
macro(_find_target_convert_to_blankable var value)
	if(DEFINED ${var})
		if(${var})
			set(${var} "${value}")
		else()
			set(${var} "")
		endif()
	endif()
endmacro()
macro(_find_target_convert_to_blankable_v2 boolvar outvar value)
	if(${boolvar})
		set(${outvar} "${value}")
	endif()
endmacro()
